import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export const revalidate = 0
export function GET(request: NextRequest) {

    let items = [
        "Tripping over a banana peel",
        "Tickling a sleeping dragon",
        "Getting tangled in a jump rope",
        "Falling into a puddle of spaghetti",
        "Being chased by a flock of angry geese",
        "Slipping on a bar of soap in the shower",
        "Inhaling helium and floating away",
        "Getting trapped in a giant bubble",
        "Accidentally swallowing a watermelon seed and growing a watermelon in their stomach",
        "Turning invisible but forgetting how to turn back",
        "Trying to ride a wild squirrel like a horse",
        "Falling into a bottomless pit of marshmallows",
        "Mistaking dynamite for a birthday candle",
        "Getting stuck inside a giant balloon",
        "Trying to juggle chainsaws",
        "Falling into a pile of feathers and suffocating",
        "Being chased by a swarm of angry bees",
        "Squeezing into a mailbox and getting stuck",
        "Sleeping through a tornado alarm",
        "Slipping on a banana peel while riding a unicycle",
        "Accidentally swallowing a fly and starting to buzz",
        "Being mistaken for a piñata at a birthday party",
        "Getting tangled in a yo-yo string and being pulled into space",
        "Trying to pet a porcupine",
        "Eating way too much cotton candy and floating away",
        "Falling into a pool of chocolate and drowning in sweetness",
        "Mistaking a crocodile for a floating log and trying to ride it",
        "Attempting to lick their elbow and getting stuck in that position",
        "Playing hide-and-seek in a washing machine and accidentally getting turned on",
        "Trying to ride a roller coaster made of rubber bands",
        "Eating a whole watermelon and turning into a human watermelon",
        "Taking a nap on a railway track",
        "Trying to catch a falling piano like in the cartoons",
        "Mixing up a potion that turns you into a chicken",
        "Trying to high-five a bee",
        "Swallowing a squeaky toy and squeaking with every breath",
        "Getting lost in a corn maze and never finding their way out",
        "Mistaking a skunk for a fluffy cat and trying to cuddle it",
        "Attempting to hula hoop with a flaming hula hoop",
        "Eating a whole jar of chili peppers and breathing fire",
        "Trying to ride a bicycle with square wheels",
        "Mistaking a bull for a large dog and trying to ride it like a rodeo cowboy",
        "Falling asleep on a giant stack of pancakes and suffocating",
        "Playing leapfrog with a charging rhinoceros",
        "Trying to catch a falling anvil",
        "Getting lost in their own daydream and forgetting to do anything else",
        "Accidentally supergluing their hands to their face",
        "Trying to balance on a tightrope made of spaghetti",
        "Mistaking a volcano for a hot tub",
        "Sticking their head inside a beehive to see what's buzzing",
        "Trying to swing on a tree branch that turns out to be a snake",
        "Falling into a giant bowl of pudding and drowning in deliciousness",
        "Attempting to juggle flaming torches made of ice cream",
        "Playing soccer with a porcupine as the ball",
        "Trying to eat an entire pizza in one bite",
        "Mistaking a venomous snake for a fashionable belt",
        "Being chased by a herd of stampeding turtles",
        "Attempting to perform a magic trick with real lions",
        "Falling into a hole filled with bouncy balls and getting trapped",
        "Trying to build a sandcastle in a hurricane",
        "Slipping on a banana peel and crashing into a cake shop",
        "Mistaking a lion for a friendly cat and trying to give it a belly rub",
        "Attempting to eat an entire watermelon in one gulp",
        "Falling into a pit of quicksand made of chocolate syrup",
        "Trying to jump over a canyon but only making it halfway",
        "Mistaking a beehive for a piñata and trying to break it open",
        "Being chased by a swarm of angry ladybugs",
        "Attempting to juggle flaming swords",
        "Falling off a tightrope made of spaghetti noodles",
        "Trying to catch a falling star and getting burned",
        "Getting tangled in a giant spider web",
        "Mistaking a shark for a friendly dolphin and trying to ride it",
        "Attempting to swim across a lake filled with jelly",
        "Falling into a giant bowl of soup and drowning in it",
        "Trying to wrestle an alligator while wearing a chicken costume",
        "Mistaking a bull for a large dog and trying to take it for a walk",
        "Attempting to eat an entire birthday cake in one bite",
        "Falling into a giant bowl of fruit salad and suffocating",
        "Trying to play basketball with a bowling ball",
        "Mistaking a crocodile for a floating log and trying to use it as a floatation device",
        "Being chased by a swarm of angry butterflies",
        "Attempting to balance on a tightrope made of licorice",
        "Falling into a pool of soda and fizzing away",
        "Trying to ride a dolphin like a horse",
        "Eating a whole jar of hot sauce and breathing fire like a dragon",
        "Mistaking a porcupine for a fluffy pillow and trying to rest their head on it",
        "Attempting to hula hoop with a chain saw",
        "Falling asleep on a roller coaster and waking up in a different city",
        "Trying to catch a falling meteor",
        "Getting lost in a maze made of giant bubble gum",
        "Mistaking a swarm of bees for a friendly cloud and trying to hug it",
        "Attempting to blow up a balloon until it pops",
        "Falling into a pit of feathers and getting buried alive",
        "Trying to ride a bicycle with no wheels",
        "Eating a whole jar of pickles and turning into one",
        "Mistaking a snake for a fashionable belt and wrapping it around their waist",
        "Attempting to jump over a canyon but coming up short and falling in",
        "Falling into a pit of giant marshmallows and getting stuck",
        "Trying to catch a falling meteor with a butterfly net",
        "Getting tangled in a jump rope and tripping over their own feet",
    ]
    return NextResponse.json(
        {
            body: items[Math.floor(Math.random() * items.length)],
        },
        {
            status: 200,
            headers: {
                'Cache-Control': 'private, no-cache, s-maxage=0, max-age=0',
            },
        },
    );
}