import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export const revalidate = 0
export function GET(request: NextRequest) {

    let items = [
        "Liam",
        "Emma",
        "Noah",
        "Olivia",
        "Oliver",
        "Ava",
        "Elijah",
        "Isabella",
        "William",
        "Sophia",
        "James",
        "Mia",
        "Benjamin",
        "Charlotte",
        "Lucas",
        "Amelia",
        "Henry",
        "Harper",
        "Alexander",
        "Evelyn",
        "Michael",
        "Abigail",
        "Daniel",
        "Emily",
        "Matthew",
        "Elizabeth",
        "Aiden",
        "Sofia",
        "Joseph",
        "Avery",
        "Samuel",
        "Ella",
        "David",
        "Scarlett",
        "Jackson",
        "Grace",
        "Sebastian",
        "Chloe",
        "Carter",
        "Victoria",
        "Jayden",
        "Riley",
        "John",
        "Aria",
        "Luke",
        "Lily",
        "Anthony",
        "Zoey",
        "Isaac",
        "Penelope",
        "Dylan",
        "Lillian",
        "Wyatt",
        "Layla",
        "Andrew",
        "Nora",
        "Joshua",
        "Aubrey",
        "Gabriel",
        "Camila",
        "Nathan",
        "Hannah",
        "Grayson",
        "Mila",
        "Eli",
        "Stella",
        "Samuel",
        "Aurora",
        "Christopher",
        "Savannah",
        "Jack",
        "Paisley",
        "Leo",
        "Brooklyn",
        "Isaac",
        "Bella",
        "Jonathan",
        "Alexa",
        "Jaxon",
        "Ellie",
        "Julian",
        "Scarlett",
        "Matthew",
        "Aurora",
        "Levi",
        "Naomi",
        "Aaron",
        "Maya",
        "Charles",
        "Hailey",
        "Cameron",
        "Elena",
        "Isaiah",
        "Sarah",
        "Connor",
        "Victoria",
        "Jeremiah",
        "Claire",
        "Josiah",
        "Audrey"
    ]
    return NextResponse.json(
        {
            body: items[Math.floor(Math.random() * items.length)],
        },
        {
            status: 200,
            headers: {
                'Cache-Control': 'private, no-cache, s-maxage=0, max-age=0',
            },
        },
    );
}