import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export const revalidate = 0
export function GET(request: NextRequest) {

    let items = [
        "Felt disappointed",
        "Cursed their luck",
        "Regretted their decision",
        "Sulked in frustration",
        "Blamed themselves",
        "Mourned their loss",
        "Accepted defeat",
        "Became dejected",
        "Questioned their choices",
        "Wished for a different outcome",
        "Brooded over the loss",
        "Dwelled on what could have been",
        "Beat themselves up mentally",
        "Wallowed in self-pity",
        "Sighed in resignation",
        "Ranted about their bad luck",
        "Shut down emotionally",
        "Sought comfort from friends",
        "Ventured into self-reflection",
        "Found solace in commiseration",
        "Analyzed their mistakes",
        "Reflected on their strategy",
        "Reconsidered their approach",
        "Experienced a sense of defeat",
        "Learned a hard lesson",
        "Contemplated their next move",
        "Assessed the risks they took",
        "Became more cautious",
        "Evaluated their chances",
        "Consoled themselves with a drink",
        "Tried to maintain a composed facade",
        "Laughed at their misfortune",
        "Shared their loss on social media",
        "Engaged in self-deprecating humor",
        "Found support in online communities",
        "Reassured themselves that it's just a game",
        "Took a break from gambling",
        "Learned from more experienced players",
        "Developed a renewed determination",
        "Channeled their disappointment into motivation",
        "Explored other hobbies or interests",
        "Seeked advice from gambling experts",
        "Reevaluated their financial decisions",
        "Grappled with feelings of regret",
        "Recounted their loss to loved ones",
        "Shared their experience as a cautionary tale",
        "Looked for opportunities to bounce back",
        "Resolved to make smarter bets in the future",
        "Considered seeking professional help for gambling addiction",
        "Attended support groups for problem gamblers",
        "Confided in a therapist about their loss",
        "Reconciled with the unpredictability of gambling",
        "Engaged in mindfulness practices to find inner peace",
        "Found comfort in the company of trusted friends",
        "Redefined their relationship with gambling",
        "Gave themselves time to heal emotionally",
        "Dissected the game and analyzed their opponents' strategies",
        "Revisited their approach to managing finances",
        "Realized that losing is an inherent part of gambling",
        "Engaged in self-care activities to boost their mood",
        "Embraced a healthier perspective on winning and losing",
        "Considered alternative forms of entertainment",
        "Tried their hand at a different type of gambling",
        "Participated in charity events to gain a sense of purpose",
        "Took responsibility for their own actions and decisions",
        "Adjusted their expectations for future gambling endeavors",
        "Challenged themselves to learn from setbacks",
        "Found inspiration in stories of successful comebacks",
        "Embraced the thrill of the game regardless of the outcome",
        "Made peace with the unpredictability of chance",
        "Reframed their perspective on money as a means, not an end",
        "Celebrated the excitement and joy of gambling itself",
        "Turned their focus toward personal growth and self-improvement",
        "Rediscovered other passions and hobbies outside of gambling",
        "Embraced a mindset of perseverance and resilience",
        "Discovered valuable life lessons through the experience of losing",
        "Recognized the importance of responsible gambling practices",
        "Embraced the camaraderie and shared experiences with fellow gamblers",
        "Channeled their energy into constructive activities",
        "Found motivation in the pursuit of future successes",
        "Learned to appreciate the process and journey, rather than solely focusing on the outcome",
        "Engaged in critical self-reflection to identify areas for improvement",
        "Set realistic goals and expectations for future gambling endeavors",
        "Found solace in the support of loved ones and friends",
        "Let go of any bitterness or resentment from the loss",
        "Embraced a mindset of continuous learning and growth",
        "Reassessed their priorities and values in life",
        "Acknowledged that losing is an opportunity for growth and self-discovery",
        "Developed a more balanced approach to risk-taking",
        "Took time to recharge and regain emotional equilibrium",
        "Reconnected with activities and hobbies that bring joy and fulfillment",
        "Expanded their knowledge and understanding of the gambling industry",
        "Developed a stronger sense of resilience and determination",
        "Accepted that losses are part of the journey to eventual success",
        "Gained a deeper appreciation for the experience itself, regardless of the outcome",
        "Reinforced their commitment to responsible gambling practices",
        "Explored strategies to minimize potential losses in future gambling endeavors",
        "Found solace in the support of gambling helplines or counseling services",
        "Realigned their focus towards long-term financial stability",
        "Reinvested their energy into personal growth and self-improvement",
        "Channeled their disappointment into productive pursuits",
        "Sought inspiration from stories of individuals who overcame setbacks",
        "Reevaluated their approach to risk assessment and management",
        "Focused on developing a healthier relationship with money",
        "Sought mentorship or guidance from seasoned gamblers",
        "Embraced a mindset of gratitude for the opportunity to participate",
        "Rediscovered the joy of simple pleasures outside of gambling",
        "Developed a stronger sense of self-discipline and restraint",
        "Reevaluated their motivations and intentions for engaging in gambling",
        "Found strength in their ability to bounce back from adversity",
        "Recognized the importance of setting realistic expectations",
        "Redirected their attention towards meaningful relationships and experiences",
        "Acknowledged the valuable life lessons that losing can teach",
        "Explored new strategies and approaches for future gambling endeavors",
        "Embraced a more balanced perspective on winning and losing",
        "Discovered alternative forms of entertainment that bring fulfillment",
        "Focused on building a solid foundation of financial literacy",
        "Cultivated a stronger sense of self-awareness and emotional resilience",
        "Reconnected with their core values and priorities in life",
        "Took steps to ensure responsible gambling habits in the future",
        "Nurtured a positive and healthy mindset for future gambling experiences",
        "Engaged in acts of kindness and giving to lift their spirits",
        "Explored different hobbies and activities to regain a sense of joy",
        "Reframed their perspective on luck and chance as part of life's journey",
        "Found inspiration in the success stories of others who faced similar setbacks",
        "Took time for self-care and self-reflection to heal and recharge",
        "Refocused their energies on personal growth and self-improvement",
        "Sought support and guidance from professionals specializing in gambling-related matters",
        "Reestablished a healthy balance between gambling and other aspects of life",
        "Found solace and understanding in support groups for individuals facing similar challenges",
        "Cultivated a sense of gratitude for the lessons learned from the loss",
        "Made a commitment to engage in responsible gambling practices",
    ]
    return NextResponse.json(
        {
            body: items[Math.floor(Math.random() * items.length)],
        },
        {
            status: 200,
            headers: {
                'Cache-Control': 'private, no-cache, s-maxage=0, max-age=0',
            },
        },
    );
}