import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export const revalidate = 0
export function GET(request: NextRequest) {

    let items = [
        "Felt elated",
        "Jumped for joy",
        "Celebrated with friends",
        "Screamed in excitement",
        "Laughed uncontrollably",
        "Raised their hands in victory",
        "Hugged their loved ones",
        "Smiled from ear to ear",
        "Did a happy dance",
        "Shouted with delight",
        "Clapped their hands",
        "Shed tears of joy",
        "High-fived fellow gamblers",
        "Called their family to share the news",
        "Took a deep breath to let it sink in",
        "Ran around in excitement",
        "Shared their win on social media",
        "Treated themselves to a special gift",
        "Splurged on a luxury item",
        "Went on a celebratory trip",
        "Popped a bottle of champagne",
        "Ordered an extravagant meal",
        "Received congratulations from others",
        "Sent thank-you messages to supporters",
        "Took a victory lap",
        "Felt a surge of adrenaline",
        "Basked in the glory of success",
        "Couldn't stop smiling",
        "Posted a winning selfie",
        "Counted their winnings repeatedly",
        "Went on a shopping spree",
        "Bought tickets to a favorite show",
        "Upgraded their living arrangements",
        "Treated friends to a night out",
        "Made charitable donations",
        "Invested in a new venture",
        "Felt a sense of accomplishment",
        "Shared their winning strategy with others",
        "Made plans for the future",
        "Celebrated with a toast",
        "Felt like they were on top of the world",
        "Bought a new car",
        "Splurged on a dream vacation",
        "Booked a reservation at a fancy restaurant",
        "Felt a rush of happiness",
        "Donated to a favorite cause",
        "Went on a spontaneous adventure",
        "Had a sleepless night from excitement",
        "Shared the news with their closest friends",
        "Invested in the stock market",
        "Felt a weight lifted off their shoulders",
        "Planned for early retirement",
        "Called a financial advisor",
        "Started a college fund for their children",
        "Experienced a surge of confidence",
        "Treated themselves to a spa day",
        "Bought a piece of jewelry",
        "Felt a sense of relief",
        "Took a moment to thank their lucky stars",
        "Splurged on home renovations",
        "Bought a round of drinks for strangers",
        "Shared their success story on a blog",
        "Felt a renewed sense of motivation",
        "Pledged to pay off debts",
        "Treated themselves to a new gadget",
        "Felt a sense of validation",
        "Took their loved ones on a surprise outing",
        "Started a trust fund for their children",
        "Celebrated with a fancy dinner party",
        "Bought a designer wardrobe",
        "Felt a surge of gratitude",
        "Created a retirement plan",
        "Sponsored a charitable event",
        "Started a business venture",
        "Felt a wave of contentment",
        "Organized a grand celebration",
        "Felt like they were living in a dream",
        "Booked a private yacht excursion",
        "Splurged on front-row concert tickets",
        "Went on a shopping spree for loved ones",
        "Felt a sense of invincibility",
        "Took a helicopter tour of the city",
        "Treated themselves to a luxury spa retreat",
        "Felt a surge of empowerment",
        "Sponsored an underprivileged child",
        "Organized a charity fundraiser",
        "Felt a sense of liberation",
        "Invested in a dream project",
        "Treated themselves to a sports car",
        "Felt like they could conquer the world",
        "Went on a tropical getaway",
        "Started a philanthropic foundation",
        "Felt a rush of adrenaline like never before",
        "Bought a beachfront property",
        "Splurged on a personal chef",
        "Felt a sense of fulfillment",
        "Treated themselves to a private concert",
        "Donated to a favorite museum or art institution",
        "Felt a surge of inspiration",
        "Took a trip around the world",
        "Celebrated with a fireworks display",
        "Felt like they were floating on air",
        "Bought a luxury watch or piece of jewelry",
        "Fulfilled a lifelong dream",
        "Treated themselves to a luxury vacation home",
        "Felt like they were in a state of euphoria",
        "Donated to a medical research organization",
        "Organized a surprise party for loved ones",
        "Felt a surge of gratitude for the opportunity",
        "Treated themselves to a private island getaway",
        "Felt like their hard work had paid off",
        "Started a scholarship fund for deserving students",
        "Celebrated with a private concert from a favorite artist",
        "Felt like they were on cloud nine",
        "Bought a piece of art from a renowned artist",
        "Splurged on a customized luxury item",
        "Felt a deep sense of satisfaction",
        "Treated themselves to a first-class travel experience",
        "Donated to an animal welfare organization",
        "Felt like they had entered a new chapter of life",
        "Bought a historic property or landmark",
        "Sponsored a community development project",
        "Felt like they were invincible",
        "Organized a grand vacation for extended family",
        "Felt a profound sense of achievement",
        "Treated themselves to a private jet experience",
        "Fulfilled a lifelong passion project",
        "Felt like they were on top of the universe",
        "Donated to a clean water initiative",
        "Celebrated with a private party at a luxury venue",
        "Felt like they were living the dream they never thought possible",
        "Bought a vineyard or winery",
        "Splurged on a high-end fashion collection",
        "Felt a surge of pride in their accomplishment",
        "Treated themselves to a luxury train journey",
        "Started a foundation to support the arts",
        "Felt a deep sense of gratitude for the win",
        "Bought a private island",
        "Sponsored a sports team or event",
        "Felt like they had reached the pinnacle of success",
        "Organized a grand charitable gala",
        "Felt like they were on the cusp of greatness",
        "Treated themselves to a private chef and staff",
        "Fulfilled a philanthropic vision",
        "Felt like their dreams had come true",
        "Bought a historic artifact or collectible",
        "Splurged on a designer penthouse or mansion",
        "Felt a sense of awe and wonder",
        "Started a foundation to support education",
        "Felt like they were truly blessed with good fortune"
    ]
    return NextResponse.json(
        {
            body: items[Math.floor(Math.random() * items.length)],
        },
        {
            status: 200,
            headers: {
                'Cache-Control': 'private, no-cache, s-maxage=0, max-age=0',
            },
        },
    );
}